Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "k8s-node#{i}" do |node|

      # configure virtual machine box
      node.vm.box = "centos/7"

      # configure virtual machine host name
      node.vm.hostname = "k8s-node#{i}"

      # configure virtual machine IP address
      node.vm.network "private_network", ip: "192.168.90.#{100+i}", netmask: "255.255.255.0"

      # configure virtual machine share folder
      # node.vm.synced_folder "~/Documents/vagrant/share", "/home/vagrant/share"

      # VirtualBox-related configuration
      node.vm.provider "virtualbox" do |v|
        # configure vm name
        v.name = "k8s-node#{i}"
        # configure vm memory
        v.memory = 4096
        # configure vm CPU units
        v.cpus = 4
      end
    end
  end
end